### ISSUE TITLE
Running "Open in CS50 Lab" command via command-shift-p yields error

### ISSUE THREAD

**Issue by dmalan** [cs50/lab50.vsix#28]
<img width="256" alt="Screen Shot 2022-09-10 at 1 01 43 PM" src="https://user-images.githubusercontent.com/788678/189493951-cd428b26-cd7e-4421-85e7-00158590d7b2.png">

> Command 'Open in CS50 Lab' resulted in an error (Cannot read properties of undefined (reading 'path'))

Do we need for the command to appear in the palette at all, though, since the command alone wouldn't know which folder to open, unless we add a file dialog?

**Comment by rongxin-liu** [comment]
Ah, suppressed!
[https://github.com/cs50/lab50.vsix/commit/f887a94b9c4fb1eca0e7703a0c2295f9ed36a9f3](https://github.com/cs50/lab50.vsix/commit/f887a94b9c4fb1eca0e7703a0c2295f9ed36a9f3)

**Comment by dmalan** [comment]
Do we definitely need it in commandPalette at all?

**Comment by rongxin-liu** [comment]
We don't need it. But once we contribute a command, it will appear in the command pallet. If you look at our `package.json` file, we don't contribute anything to the command palette, yet the command still appears in the command pallet.

That's why we need another command pallet contribution to suppress it.

**Comment by dmalan** [comment]
Gotcha!
