### ISSUE TITLE
Is there a way for the + icon in the console to open a new shell in the same directory as the foregrounded shell?

### ISSUE THREAD

**Issue by dmalan** [cs50/lab50.vsix#5]

**Comment by rongxin-liu** [comment]
I went through VS Code's terminal settings and there isn't a way to do it natively. It only allows customizing `cwd` when launching a new terminal via setting `terminal.integrated.cwd`.

**Comment by dmalan** [comment]
Should we set that whenever a lab is open?

**Comment by rongxin-liu** [comment]
What do you think? I'm leaning toward not setting it, but we could set it if we want to.

If we do this, we will be touching workspace's `settings.json` file and setting/removing (or restoring) `terminal.integrated.cwd` value when the lab is opened/closed.

The catch is student could be closing VS Code without closing the lab explicitly, which would leave `terminal.integrated.cwd` still set to the previous lab location. No big deal on our Codespace since we could have cs50.vsix extension to always reset `terminal.integrated.cwd` to our default workspace location (which just simply removing `terminal.integrated.cwd` from `settings.json` so it default back to /workspaces/USER_ID)

In the local VS Code scenario, though, we could only rely on lab50.vsix to maintain`terminal.integrated.cwd`.

**Comment by rongxin-liu** [comment]
Another way to do this is to perhaps contribute a button to the terminal view when the lab is opened and clicking that button would always make a new terminal in the same lab location.

**Comment by dmalan** [comment]
Okay, let's leave as is for now and reassess if actually an issue!
